global using CompanyManagement.Core.DataAccess.Interfaces;
global using CompanyManagement.Core.Entities.Base;
global using CompanyManagement.Core.Enums;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using System.Linq.Expressions;
global using Microsoft.AspNetCore.Identity;
global using CompanyManagement.Entities.Enums;
global using Microsoft.AspNetCore.Http;